FROM osgeo/gdal:ubuntu-small-latest

LABEL maintainer="Ben Mack"
LABEL nasa_hls_jupyterlab='0.1.1'


RUN apt-get update \
 && apt-get install python3-pip -y

WORKDIR /home/hls

COPY . /home/hls/nasa_hls
COPY ./docs/tutorials /home/hls/tutorials

RUN pip3 install -r /home/hls/nasa_hls/requirements-dev.txt

RUN pip3 install -e /home/hls/nasa_hls

EXPOSE 8888
CMD jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
