FROM benmack/nasa-hls:2020-08-23

LABEL maintainer="Ben Mack"
LABEL nasa-hls-jupyterlab='2020-08-23'

COPY ./docs/tutorials /home/hls/tutorials
COPY ./requirements-dev.txt /home/hls/nasa_hls/requirements-dev.txt

RUN pip3 install -r /home/hls/nasa_hls/requirements-dev.txt

EXPOSE 8888
CMD jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
